### ISSUE TITLE
nodeschool feb 2016 (#12)

### ISSUE THREAD

**Issue by gautamarora** [nodeschool/nyc#16]
**Date:**

- Feb 25

**Workshops:**

1. javascripting
1. learnyounode
1. count-to-6
1. expressworks

**Tasks:**

- [x] :calendar: Set a date
- [x] :blue_book: Create meetup page
- [x] :mega: Call for mentors
- [ ] :school: :statue_of_liberty: Post event on nodeschool.io
- [ ] :speech_balloon: Post to gitter channel
- [ ] :octocat: Inform on GitHub
- [ ] :envelope: Inform about event through mail
- [ ] :bird: Tweet about the event
- [ ] :house: Update homepage
- [ ] :email: send attendee list to security
- [ ] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

**Confirmed Mentors:**

1. @gautamarora
1. @mmwtsn 
1. @tapsboy 
1. @retrohacker 
1. @ChrisMLee 
1. @evelynStraigt 
1. @stefania11  
1. @gilchenzion 
1. @amejias101 
1. @cormickjbrowne 

/cc @acingraham

**Comment by gautamarora** [comment]
I will be there & have completed JS, Node, ES6, Express workshops.

**Comment by mmwtsn** [comment]
I'm available to mentor and have completed the workshops listed above.

**Comment by tapsboy** [comment]
I will be there

**Comment by retrohacker** [comment]
I'll be there, and have completed all 4 workshops.

**Comment by ChrisMLee** [comment]
I'm available to mentor and have completed all of the listed workshops

**Comment by gautamarora** [comment]
@mmwtsn @tapsboy @retrohacker @ChrisMLee :+1:

**Comment by evelynStraigt** [comment]
Will be available to mentor all listed workshops.  (=

**Comment by stefania11** [comment]
Will be there and available to mentor all listed workshops

**Comment by gilchenzion** [comment]
Will be able to mentor all workshops

**Comment by amejias101** [comment]
Will be able to mentor all workshops as well.

**Comment by gautamarora** [comment]
@evelynStraigt @stefania11 @gilchenzion @amejias101 :+1:

**Comment by cormickjbrowne** [comment]
I can mentor and I've completed all 4 workshops.

**Comment by gautamarora** [comment]
wow! 10 mentors! i'm sure we are running out of capes for this one! :+1:

**Comment by gautamarora** [comment]
thank you mentors! it was a great event!
