### ISSUE TITLE
nodeschool mar 2016

### ISSUE THREAD

**Issue by gautamarora** [nodeschool/nyc#19]
**Date:**

- Mar 17

**Event Page:**
- [Meetup](http://www.meetup.com/NY-JavaScript/events/227502760/)

**Workshops:**

1. javascripting
1. learnyounode
1. count-to-6
1. es-next-generation (featured)

**Tasks:**

- [x] :calendar: Set a date
- [x] :blue_book: Create meetup page
- [x] :mega: Call for mentors
- [ ] :school: :statue_of_liberty: Post event on nodeschool.io
- [ ] :speech_balloon: Post to gitter channel
- [ ] :octocat: Inform on GitHub
- [ ] :envelope: Inform about event through mail
- [ ] :bird: Tweet about the event
- [ ] :house: Update homepage
- [ ] :email: send attendee list to security
- [ ] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

**Organizers:**

1. @jovena
1. @acingraham 
1. @gautamarora

**Confirmed Mentors:**

1. @gautamarora
1. @evelynStraigt 
1. @retrohacker 
1. @gilchenzion 
1. @adobley 
1. @mmwtsn 
1. @ChrisMLee

**Comment by gautamarora** [comment]
Call for Mentors: @acingraham @designMoreWeb @mmwtsn @retrohacker @ChrisMLee @evelynStraigt @stefania11 @gilchenzion @amejias101@cormickjbrowne

**Comment by gautamarora** [comment]
I'm available to mentor & have completed JS, Node, ES6, ES-Next-Gen workshops.

**Comment by gautamarora** [comment]
p.s. if you are not on the call for mentors list but are interested to mentor (at this event or in future), just message me and i will add you to the list.

**Comment by evelynStraigt** [comment]
I'll be there.  (=

**Comment by janecakemaster** [comment]
i'll be there!

**Comment by janecakemaster** [comment]
actually.. how long does this event go? just realized i also have a brooklynjs ticket. i can probably do both but i'd need to know about timing

**Comment by retrohacker** [comment]
Count me in!

**Comment by amejias101** [comment]
I also got a Brooklynjs ticket, probably will not be able to make it to the
meetup :|

**Comment by gautamarora** [comment]
@janecakemaster - nodeschool goes from 6:30 - 9:30

**Comment by gautamarora** [comment]
@retrohacker :+1:

**Comment by gautamarora** [comment]
@amejias101 have fun at brooklynjs! see you at the next nodeschool

**Comment by adobley** [comment]
Do you have space for another mentor?

**Comment by gilchenzion** [comment]
I'll be there

On Fri, Mar 11, 2016 at 7:01 PM, Aidan Obley <notifications@github.com>
wrote:

> Do you have space for another mentor?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/nyc/issues/19#issuecomment-195608505>.
>



-- 
Gil Chen-Zion
Software Engineer, Oscar Insurance
Twitter <https://twitter.com/gilcz2> | LinkedIn
<https://www.linkedin.com/in/gilchenzion>

**Comment by gautamarora** [comment]
@adobley - we do! Could you confirm if you have done (or could do before the event) the javascripting, learnyounode & count-to-6 workshops? Those are the core workshops at every event and we have all mentors finish them to be able to answer help answer a diverse set of wuestions from students.

**Comment by gautamarora** [comment]
Correction: ...we have all mentors finish them to be able to help answer a diverse set of questions from students.

**Comment by adobley** [comment]
Yes I have. I'm the founder/organizer of nodeschool philadelphia =) I just happen to be in town so I wanted to help out.

**Comment by mmwtsn** [comment]
@gautamarora I can mentor this week as well. I completed javascripting, learnyounode, count-to-6, and the other generators workshop. I'll take a look at es-next-generation before the 17th!

**Comment by gautamarora** [comment]
@adobley awesome! look forward to meeting you! We handle RSVP's via meetup. Can you join us at http://www.meetup.com/NY-JavaScript/ and I will add you to the event.

**Comment by gautamarora** [comment]
@mmwtsn :+1:

**Comment by adobley** [comment]
@gautamarora Joined up, thanks!

**Comment by gautamarora** [comment]
@adobley added you to the event on meetup. See you on thursday.

**Comment by ChrisMLee** [comment]
@gautamarora I'm available to mentor and have completed all of the listed workshops.

**Comment by gautamarora** [comment]
@ChrisMLee sorry, just seeing this. Can you make it today?

**Comment by ChrisMLee** [comment]
@gautamarora Yep see you there

**Comment by gautamarora** [comment]
Thank you mentors! @mmwtsn @ChrisMLee @adobley. We're seeing great feedback from students on meetup!
