### ISSUE TITLE
nodeschool apr 2016

### ISSUE THREAD

**Issue by gautamarora** [nodeschool/nyc#20]
**Date:**
- Apr 21

**Event Page:**
- [Meetup](http://www.meetup.com/NY-JavaScript/events/227502881/)

**Workshops:**
1. javascripting
2. learnyounode
3. count-to-6
4. functional-javascript

**Tasks:**
- [x] :calendar: Set a date
- [x] :blue_book: Create meetup page
- [x] :mega: Call for mentors
- [ ] :school: :statue_of_liberty: Post event on nodeschool.io
- [ ] :speech_balloon: Post to gitter channel
- [ ] :octocat: Inform on GitHub
- [ ] :envelope: Inform about event through mail
- [ ] :bird: Tweet about the event
- [ ] :house: Update homepage
- [ ] :email: send attendee list to security
- [ ] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

**Organizers:**
1. @jovena
2. @acingraham 
3. @gautamarora

**Confirmed Mentors:**
1. @acingraham 
2. @designMoreWeb
3. @cormickjbrowne
4. @mmwtsn 
5. @janecakemaster

**Comment by gautamarora** [comment]
Call for Mentors: @acingraham @designMoreWeb @mmwtsn @retrohacker @ChrisMLee @evelynStraigt @stefania11 @gilchenzion @amejias101 @cormickjbrowne @orangejulius @tapsboy

**Comment by acingraham** [comment]
Count me in!

**Comment by mmwtsn** [comment]
I'm in!

**Comment by retrohacker** [comment]
I'll be traveling for work this week :disappointed: sorry!

**Comment by designMoreWeb** [comment]
IN

**Comment by janecakemaster** [comment]
shweet i'm in!

**Comment by cormickjbrowne** [comment]
I should already be in.

**Comment by gautamarora** [comment]
thanks @mmwtsn @designMoreWeb @janecakemaster @cormickjbrowne !!

**Comment by gautamarora** [comment]
@ChrisMLee @orangejulius @amejias101 @stefania11 @adobley - can you make it for NodeSchool tomorrow?

**Comment by amejias101** [comment]
Sorry, I can't make it this month. I hope that you guys have fun though!
