### ISSUE TITLE
nodeschool jun 2016

### ISSUE THREAD

**Issue by gautamarora** [nodeschool/nyc#21]
**Date:**
- Jun 16

**Event Page:**
- [Meetup](http://www.meetup.com/NY-JavaScript/events/227503383/)
- _RSVPs not open yet_

**Workshops:**
1. javascripting
2. learnyounode
3. count-to-6
4. stream-adventure

**Tasks:**
- [x] :calendar: Set a date
- [x] :blue_book: Create meetup page
- [ ] :mega: Call for mentors
- [ ] :school: :statue_of_liberty: Post event on nodeschool.io
- [ ] :speech_balloon: Post to gitter channel
- [ ] :octocat: Inform on GitHub
- [ ] :envelope: Inform about event through mail
- [ ] :bird: Tweet about the event
- [ ] :house: Update homepage
- [ ] :email: send attendee list to security
- [ ] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

**Organizers:**
1. @jovena
2. @acingraham 
3. @gautamarora

**Comment by retrohacker** [comment]
Doing a call for mentors?

I'll be there :smile:

**Comment by cormickjbrowne** [comment]
I'll mentor.
